"""Build the compatibility version of the site (works in browsers without scroll-driven animation).

    python3 scripts/compat-build.py [target-dir]      # default: "." = patch the site root in place

What it does, and nothing else:
  * copies the site into the target directory (skipped when the target is ".")
  * appends a generated, marker-delimited block to styles.css:
      - a copy of every scroll-driven rule, gated to <html class="sd-poly"> (the browser's own @supports blocks are
        left untouched, so Chrome and Safari 26 run exactly what they ran before). In the copy, animation-range is
        stored as --sd-range and each rule is paused with a 1s duration; scripts/sd.js then sets each animation's
        time from the scroll position.
      - the header rules for modes without native scroll timelines
      - the static layout (the plain page) used when nothing animated can run
  * adds the mode-picking script to the top of <head> in index.html and loads assets/sd.js at the end of <body>.
Idempotent: re-running replaces the generated block and the injected tags."""
import re, shutil, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
target = sys.argv[1] if len(sys.argv) > 1 else '.'
T = os.path.join(ROOT, target)
inplace = os.path.abspath(T) == ROOT

HEAD_START, HEAD_END = '<!-- SD-HEAD-START -->', '<!-- SD-HEAD-END -->'
BODY_START, BODY_END = '<!-- SD-BODY-START -->', '<!-- SD-BODY-END -->'
CSS_START, CSS_END = '/* SD-COMPAT-START (generated by scripts/compat-build.py) */', '/* SD-COMPAT-END */'

HEAD = '''<script>
/* Pick how the drawing runs: native scroll-driven animation, the scripted version, or the plain static page. */
(function () {
  var cl = document.documentElement.classList;
  try {
    var reduce = window.matchMedia && matchMedia('(prefers-reduced-motion: reduce)').matches;
    var ok = !!(window.CSS && CSS.supports);
    var native = ok && CSS.supports('animation-timeline', 'view()') && CSS.supports('animation-timeline', 'scroll()');
    var poly = ok && 'getAnimations' in Element.prototype && !!CSS.registerProperty &&
      CSS.supports('offset-path', 'path("M0 0")') && CSS.supports('animation-play-state', 'paused');
    var m = reduce ? 'static' : native ? 'native' : poly ? 'poly' : 'static';
    // the scripted mode starts as the safe static page and switches on only once assets/sd.js has really built it
    if (m === 'poly') { cl.add('sd-static'); cl.add('sd-want-poly'); } else cl.add('sd-' + m);
  } catch (e) { cl.add('sd-static'); }
})();
</script>'''
BODY = '<script src="./assets/sd.js" defer></script>'


# ---------------------------------------------------------------- css helpers
def match_brace(s, i):
    """index of the } that closes the { at s[i]"""
    d = 0
    for j in range(i, len(s)):
        if s[j] == '{': d += 1
        elif s[j] == '}':
            d -= 1
            if d == 0: return j
    raise ValueError('unbalanced braces')


def supports_blocks(css, cond):
    """inner text of every @supports <cond> { ... } block"""
    out, pos = [], 0
    key = '@supports ' + cond
    while True:
        i = css.find(key, pos)
        if i < 0: return out
        b = css.index('{', i)
        e = match_brace(css, b)
        out.append(css[b + 1:e]); pos = e + 1


def split_rules(inner):
    """[(comment, selector, body)] for a flat list of rules"""
    rules, i = [], 0
    while i < len(inner):
        m = re.match(r'\s*', inner[i:]); i += m.end()
        if i >= len(inner): break
        if inner.startswith('/*', i):
            j = inner.index('*/', i) + 2
            rules.append(('c', inner[i:j], None)); i = j; continue
        b = inner.index('{', i); e = match_brace(inner, b)
        rules.append(('r', inner[i:b].strip(), inner[b + 1:e])); i = e + 1
    return rules


# Animations that only change a custom property are driven from sd.js as inline custom properties instead:
# Firefox does not re-read var() inside the keyframes of other animations when such a property is animated.
VARS = {'calm': ('--amp', '1', '0'), 'calm-m': ('--amp', '0.5', '0'), 'walk-on': ('--walk', '0', '1'), 'pace-on': ('--pace', '0', '1')}


def split_vars(body):
    mn = re.search(r'animation-name:\s*([^;]+);', body)
    if not mn: return body
    names = [n.strip() for n in mn.group(1).split(',')]
    if not any(n in VARS for n in names): return body
    mr = re.search(r'--sd-range:\s*([^;]+);', body)
    ranges = [r.strip() for r in mr.group(1).split(',')] if mr else None
    keep_n, keep_r, vars_ = [], [], []
    for i, n in enumerate(names):
        if n in VARS:
            if ranges is not None:
                prop, a, b = VARS[n]; vars_.append('%s %s %s %s' % (prop, a, b, ranges[i]))
        else:
            keep_n.append(n)
            if ranges is not None: keep_r.append(ranges[i])
    body = body.replace(mn.group(0), 'animation-name: %s;' % ', '.join(keep_n))
    if mr:
        body = body.replace(mr.group(0), '--sd-range: %s;' % ', '.join(keep_r) + ('\n      --sd-vars: %s;' % ', '.join(vars_) if vars_ else ''))
    return body


def to_poly(inner):
    out = []
    for kind, sel, body in split_rules(inner):
        if kind == 'c':
            continue
        had_timeline = 'animation-timeline' in body
        body = re.sub(r'animation-timeline:[^;]*;', '', body)
        body = re.sub(r'view-timeline-[a-z]+:[^;]*;', '', body)
        had_range = 'animation-range:' in body
        body = re.sub(r'animation-range:([^;]*);', r'--sd-range:\1;', body)
        body = split_vars(body)
        if had_timeline or had_range:
            body = body.rstrip() + '\n      animation-duration: 1s; animation-delay: 0s; animation-iteration-count: 1; animation-play-state: paused;\n    '
        if not body.strip(' \n;'):
            continue   # e.g. .flow { view-timeline-name... } leaves nothing
        sels = ', '.join('html.sd-poly ' + s.strip() for s in sel.split(','))
        out.append('  %s {%s}' % (sels, body))
    return '\n'.join(out)


STATIC = '''
/* ---- header in modes without native scroll timelines: white over the film, dark once past it (set by sd.js) ---- */
@media (min-width: 901px), (min-aspect-ratio: 10001/10000) {
  html:not(.sd-native) .topbar { mix-blend-mode: normal; }
  html:not(.sd-native) .topbar .brand svg { filter: drop-shadow(0 1px 5px rgba(0, 0, 0, 0.35)); transition: filter 250ms var(--ease); }
  html:not(.sd-native) .topbar .brand, html:not(.sd-native) .topbar .contact { transition: color 250ms var(--ease), text-shadow 250ms var(--ease); }
  html:not(.sd-native) .topbar .contact { text-shadow: 0 1px 8px rgba(0, 0, 0, 0.4); }
  html:not(.sd-native).hdr-dark .topbar .brand, html:not(.sd-native).hdr-dark .topbar .contact { color: var(--ink); text-shadow: none; }
  html:not(.sd-native).hdr-dark .topbar .brand svg { filter: drop-shadow(0 1px 5px rgba(0, 0, 0, 0)); }
}

/* ---- the plain page: no drawing, the three sections as ordinary blocks (also the no-script default) ---- */
html:not(.sd-native):not(.sd-poly) .hero,
html:not(.sd-native):not(.sd-poly) .line,
html:not(.sd-native):not(.sd-poly) .trail-fade,
html:not(.sd-native):not(.sd-poly) .trail-fade-d { display: none !important; }
html:not(.sd-native):not(.sd-poly) .flow { width: min(40rem, 100% - 48px); padding: clamp(64px, 12vh, 128px) 0 clamp(8px, 4vh, 40px); }
html:not(.sd-native):not(.sd-poly) .say,
html:not(.sd-native):not(.sd-poly) .say.left,
html:not(.sd-native):not(.sd-poly) .say.right,
html:not(.sd-native):not(.sd-poly) .say.c1,
html:not(.sd-native):not(.sd-poly) .say.c2,
html:not(.sd-native):not(.sd-poly) .say.c3 {
  position: static !important; transform: none !important; width: 100% !important; max-width: none !important;
  margin: 0 0 clamp(40px, 8vh, 72px) !important; padding: 0 !important; background: none !important; animation: none !important; opacity: 1 !important;
}
html:not(.sd-native):not(.sd-poly) .flow { display: flex; flex-direction: column; }
html:not(.sd-native):not(.sd-poly) .say.closing { order: 10; margin: clamp(72px, 14vh, 140px) 0 clamp(24px, 6vh, 56px) !important; }
html:not(.sd-native):not(.sd-poly) .say.closing h1 { max-width: 12ch; font-size: clamp(2.4rem, 8vw, 4.6rem); }
@media (max-width: 900px) and (max-aspect-ratio: 1/1) { html:not(.sd-native):not(.sd-poly) .film { min-height: 0; padding-bottom: 8px; } }
'''


def build_css(css):
    css = re.sub(re.escape(CSS_START) + r'.*?' + re.escape(CSS_END) + r'\n?', '', css, flags=re.S).rstrip('\n') + '\n'
    # the old half-built fallback (lines drawn whole, shapes solid) must not leak into the scripted mode;
    # it never applied in browsers that support scroll timelines, so this changes nothing for them
    css = css.replace('@supports not (animation-timeline: view())', '@media not all')
    desktop, phone = None, None
    for k, inner in enumerate(supports_blocks(css, '(animation-timeline: view())')):
        if '.line-m' in inner and '.l1' in inner and desktop is not None: phone = inner
        elif '.lane' in inner and phone is None and desktop is None: desktop = inner
        else: phone = inner
    assert desktop and phone, 'could not find the two view() blocks'
    block = [CSS_START,
             '@property --sd-range { syntax: "*"; inherits: false; }',
             '@property --sd-vars { syntax: "*"; inherits: false; }',
             '@keyframes sd-probe { to { opacity: 0.02; } }',
             '/* scroll-driven rules, scripted (html.sd-poly); animation-range is stored as --sd-range */',
             to_poly(desktop),
             '@media (max-width: 900px) and (max-aspect-ratio: 1/1) {',
             '  html.sd-poly .trail-fade-d { display: none; }   /* the desktop fade must not leak onto phones */',
             to_poly(phone),
             '}',
             STATIC, CSS_END, '']
    return css + '\n'.join(block)


def build_html(h):
    h = re.sub(r'\n[ \t]*' + re.escape(HEAD_START) + r'.*?' + re.escape(HEAD_END), '', h, flags=re.S)
    h = re.sub(re.escape(BODY_START) + r'.*?' + re.escape(BODY_END) + r'\n?', '', h, flags=re.S)
    vp = '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">'
    assert vp in h, 'viewport meta not found'
    h = h.replace(vp, vp + '\n  ' + HEAD_START + '\n' + HEAD + '\n  ' + HEAD_END, 1)   # after charset + viewport
    h = h.replace('</body>', BODY_START + '\n' + BODY + '\n' + BODY_END + '\n</body>', 1)
    return h


def main():
    if not inplace:
        if os.path.exists(T): shutil.rmtree(T)
        os.makedirs(T)
        for f in ('index.html', 'privacy.html', 'terms.html', 'styles.css', 'favicon.ico', 'site.webmanifest'):
            shutil.copy(os.path.join(ROOT, f), T)
        shutil.copytree(os.path.join(ROOT, 'assets'), os.path.join(T, 'assets'))
    shutil.copy(os.path.join(ROOT, 'scripts', 'sd.js'), os.path.join(T, 'assets', 'sd.js'))
    for f, fn in (('styles.css', build_css), ('index.html', build_html)):
        p = os.path.join(T, f)
        with open(p) as fh: s = fh.read()
        with open(p, 'w') as fh: fh.write(fn(s))
    print('built', target)


main()
